### ISSUE TITLE
Won't work.

### ISSUE THREAD

**Issue by ghost** [demaisj/soundcloud-rp#21] opened 2019-02-24 01:37 UTC
<img src=https://image.prntscr.com/image/HguVc97ASSO-h-mroZvNGg.png>

**Comment by demaisj** [comment] 2019-02-24 11:04
Hi,

The syntax of your config file is invalid, that's why the program crashes.
The config file must be a valid JSON file. You can check its syntax here for example : http://json.parser.online.fr/
I'm closing this issue since this is not a bug. You can still comment if you need more help!

Have a good day

**Closed as completed by demaisj** 2019-02-24 11:04 UTC

**Comment by ghost** [comment] 2019-02-24 14:48
> 
> 
> Hi,
> 
> The syntax of your config file is invalid, that's why the program crashes.
> The config file must be a valid JSON file. You can check its syntax here for example : http://json.parser.online.fr/
> I'm closing this issue since this is not a bug. You can still comment if you need more help!
> 
> Have a good day

Thanks for the reply!
My APIKey didn't had quotes, that was the problem. Thanks! But now, my CMD stays like this and it won't show anything in my Discord profile. What did I do wrong?
<img src=https://image.prntscr.com/image/vIB55TkDQRaFP39SixK0qA.png>

**Comment by demaisj** [comment] 2019-02-24 15:05
Did you install the userscript on your browser ?
If yes, you can try to run the program with the `set DEBUG=soundcloud-rp:* & npm run start` to help me get more information about your problem.

**Comment by ghost** [comment] 2019-02-27 21:25
> 
> 
> Did you install the userscript on your browser ?
> If yes, you can try to run the program with the `set DEBUG=soundcloud-rp:* & npm run start` to help me get more information about your problem.

Yes, I did. I'm using Greasemonkey instead of Tampermonkey, could that be the problem?
Also, here's a screenshot.
<img src=https://image.prntscr.com/image/HIyh6rNgSn2NlEghdqEjhg.png>

**Comment by demaisj** [comment] 2019-03-03 15:00
The userscript is working A-OK. There is a problem on the server while getting track info.
Have you double checked your soundcloud client-id ?

**Comment by ghost** [comment] 2019-03-06 01:01
> 
> 
> The userscript is working A-OK. There is a problem on the server while getting track info.
> Have you double checked your soundcloud client-id ?

I used this [method](https://stackoverflow.com/questions/40992480/getting-a-soundcloud-api-client-id) to get my client id. I did it again and it gave me another client id, but it still doesn't work.
<img src=https://i.imgur.com/0vIPzpy.png>
