### ISSUE TITLE
Chrome console spitting out errors

### ISSUE THREAD

**Issue by iCookieBG** [demaisj/soundcloud-rp#10] opened 2018-08-23 07:46 UTC
I did everything correct with no errors on the server part. Since it wasn't working, I decided to see whats in the console and this is what I found.
![blmf5ib](https://user-images.githubusercontent.com/36744788/44511987-d52a0580-a6c1-11e8-921a-a1720ba57cef.png)

**Comment by demaisj** [comment] 2018-08-23 10:36
Hi, 
The server seems to not be running, as your browser recieves no data.

**Comment by iCookieBG** [comment] 2018-08-23 12:34
But I can view http://127.0.0.1:7769/client.js

**Comment by demaisj** [comment] 2018-08-23 12:58
Have you an extension on your browser blocking requests? (like HTTPS everywhere blocking non-https requests from a https site)

**Comment by iCookieBG** [comment] 2018-08-25 13:05
Sorry for late response, and no.

**Comment by demaisj** [comment] 2018-08-26 02:43
This is a strange error.
What OS are you using? What version of nodejs, npm, chrome are you running?
Can you run the server in debug mode and tell me what it outputs? To activate debug mode you use the `set DEBUG=soundcloud-rp:* & npm run start` command on Windows, or the `DEBUG=soundcloud-rp:* npm run start` on Linux/Mac OS.

**Comment by iCookieBG** [comment] 2018-08-26 15:54
Nevermind, it randomly started working when I reinstalled nodejs. Thanks for responding tho.

**Comment by demaisj** [comment] 2018-08-26 16:06
Okay, i'm closing this issue since the problem is resolved.

**Closed by demaisj** 2018-08-26 16:06 UTC
